apiVersion: v1
kind: Service
metadata:
  name: {{ include "storehub.backend.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "storehub.labels" . | nindent 4 }}
    app: storehub-backend
spec:
  type: {{ .Values.backend.service.type }}

  # بيوصل traffic من الـ Service لـ port 5000 في الـ pod
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http

  # بيحدد أي pods ياخد traffic — اللي عندها label app=storehub-backend
  selector:
    app: storehub-backend