apiVersion: v1
kind: Secret
metadata:
  name: storehub-db-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "storehub.labels" . | nindent 4 }}
type: Opaque
stringData:
  # stringData = بتكتب plain text وKubernetes يحولها base64 لوحده
  DB_USER: {{ .Values.database.user | quote }}
  # التأكد من وجود القسم في الـ values لتفادي الـ Nil Pointer
  DB_PASSWORD: {{ if .Values.secrets }}{{ .Values.secrets.dbPassword | default "changeme" | quote }}{{ else }}"changeme"{{ end }}