apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storehub.frontend.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "storehub.labels" . | nindent 4 }}
    app: storehub-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: storehub-frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: storehub-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: 80
              protocol: TCP

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

          # الـ nginx بيرجع 200 على / لما بيكون جاهز
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10