apiVersion: v1
kind: Service
metadata:
  name: {{ include "storehub.frontend.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "storehub.labels" . | nindent 4 }}
    app: storehub-frontend
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      nodePort: 30095
      protocol: TCP
      name: http
  selector:
    app: storehub-frontend